[0m00:59:20.989360 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F968B34910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F96B315790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F96B315700>]}


============================== 00:59:20.993369 | 613c042b-c222-4223-b5ab-21079cea9cdb ==============================
[0m00:59:20.993369 [info ] [MainThread]: Running with dbt=1.8.7
[0m00:59:20.994504 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Chinki Lengkong\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:59:20.996513 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Chinki Lengkong\Documents\Projects\semantic-layer-implementation\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:59:20.997514 [debug] [MainThread]: Command `dbt run` failed at 00:59:20.997514 after 0.07 seconds
[0m00:59:20.997514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F968B34910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F96B315700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F96B529E80>]}
[0m00:59:20.998505 [debug] [MainThread]: Flushing usage events
[0m02:09:22.624486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002753F6648E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027542055B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027542055EE0>]}


============================== 02:09:22.629609 | e77a3559-096c-4905-b0b8-d6526f323190 ==============================
[0m02:09:22.629609 [info ] [MainThread]: Running with dbt=1.8.7
[0m02:09:22.630597 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Chinki Lengkong\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m02:09:22.630597 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Chinki Lengkong\Documents\Projects\semantic-layer-implementation\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:09:22.632609 [debug] [MainThread]: Command `dbt run` failed at 02:09:22.632609 after 0.07 seconds
[0m02:09:22.632609 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002753F6648E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027542036730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027542036EB0>]}
[0m02:09:22.632609 [debug] [MainThread]: Flushing usage events
